#!/bin/bash

# Target and driver details
TARGET="iqn.2005-10.org.freenas.ctl.Sanzilla:lun0"
DRIVER="iscsi"

# Define attribute keys and values
declare -A attributes=(
  ["QueuedCommands"]="128"
  ["MaxXmitDataSegmentLength"]="262144"
  ["MaxRecvDataSegmentLength"]="262144"
  ["FirstBurstLength"]="262144"
  ["MaxBurstLength"]="16776192"
)

# Loop through each attribute and set it
for key in "${!attributes[@]}"; do
  value=${attributes[$key]}
  echo "Setting attribute $key to $value"
  scstadmin -set_tgt_attr "$TARGET" -driver "$DRIVER" -noprompt -attributes "$key=$value"

  # Check if command was successful
  if [ $? -ne 0 ]; then
    echo "Failed to set attribute $key=$value"
    exit 1
  fi
done

echo "All attributes successfully set!"